# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create gradle.properties
      run: |
        echo "storeFile=$GITHUB_WORKSPACE/key.store
        storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
        keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
        keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" > $GITHUB_WORKSPACE/keystore.properties

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - run: rm -rf app/src/main/res/values-ru

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: XPrivacyLua-dev
        path: app/build/outputs/apk/release/*.apk
